{% set name = "cuda-nvml-dev" %}
{% set version = "13.1.68" %}
{% set cuda_version = "13.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvml_dev/{{ platform }}/cuda_nvml_dev-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: f6c9f839db48bc1dcb9624a6654afb5de3056334eff80be6df51a3ca8eb9266f  # [linux64]
  sha256: dfab48162fdd08a4ca12d406adf1d8fe78cff1e794c3e0e891b20d2c1b321229  # [aarch64]
  sha256: 163de253f2921e7328b6d3584f7993f57348be176308e189548bb735a0610638  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/lib/pkgconfig/nvidia-ml-*.pc                         # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libnvidia-ml.so  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/include/nvml.h             # [linux]
    - bash test-rpath.sh                                                   # [linux]
    - if not exist %LIBRARY_LIB%\{{ target_name }}\nvml.lib exit 1         # [win]
    - if not exist %LIBRARY_INC%\nvml.h exit 1    # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVML native dev links, headers
  description: |
    NVML native dev links, headers
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
