{% set name = "cuda-nvml-dev" %}
{% set version = "12.3.101" %}
{% set cuda_version = "12.3" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvml_dev/{{ platform }}/cuda_nvml_dev-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 34ab12792d46a839012236608ec446a13f6e7775556f9122a7c33bc742b3b29d  # [linux64]
  sha256: 655c44679b0d5c6f8756257770d99ba01bf31557a831076c5623b372adaaeadd  # [ppc64le]
  sha256: e14f15f6eb8dc25d37872d713bfb40530b67b68e7b8441078310f40a3aec121f  # [aarch64]
  sha256: 73fef685ec993d8abdae25e8b0b96a562811e8e3b8709f3bf97c7388234dd81d  # [win]

build:
  number: 0
  skip: true  # [osx or (linux and s390x)]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    #- arm-variant * {{ arm_variant_type }}  # [aarch64]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  commands:
    - test -f $PREFIX/lib/pkgconfig/nvidia-ml-*.pc                         # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libnvidia-ml.so  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/include/nvml.h             # [linux]
    - if not exist %LIBRARY_LIB%\nvml.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\nvml.h exit 1    # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVML native dev links, headers
  description: |
    NVML native dev links, headers
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
