schema_version: 1

context:
  version: "13.3.29"
  cuda_version: "13.3"

package:
  name: cuda-nvml-dev
  version: ${{ version }}

source:
  - if: linux64
    then:
      url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvml_dev/linux-x86_64/cuda_nvml_dev-linux-x86_64-${{ version }}-archive.tar.xz
      sha256: b62508923dadc0ac79fb1846eeb444296813cb077964e0c8348ba051bc0160aa
  - if: linux and aarch64
    then:
      url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvml_dev/linux-sbsa/cuda_nvml_dev-linux-sbsa-${{ version }}-archive.tar.xz
      sha256: 40d290c2fbabc3b559c8f5083a86adbb331a76e556914b2c46a0f0d11ca51494
  - if: win64
    then:
      url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvml_dev/windows-x86_64/cuda_nvml_dev-windows-x86_64-${{ version }}-archive.zip
      sha256: 4e1bd1c66dd66293c6d94b1ed2efa5065654533b36ccbc7477dc1f466dc3d65c

build:
  number: 1
  skip: osx or ppc64le or riscv64
  script: build
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - if: aarch64
      then: arm-variant * ${{ arm_variant_type }}
    - if: linux
      then: cf-nvidia-tools 1.*
  host:
    - cuda-version ${{ cuda_version }}.*
  run:
    - ${{ pin_compatible('cuda-version', upper_bound='x.x') }}
  run_constraints:
    - if: aarch64
      then: arm-variant * ${{ arm_variant_type }}

tests:
  - package_contents:
      files:
        - if: linux64
          then:
            - lib/pkgconfig/nvidia-ml-*.pc
            - targets/x86_64-linux/lib/stubs/libnvidia-ml.so
            - targets/x86_64-linux/include/nvml.h
        - if: linux and aarch64
          then:
            - lib/pkgconfig/nvidia-ml-*.pc
            - targets/sbsa-linux/lib/stubs/libnvidia-ml.so
            - targets/sbsa-linux/include/nvml.h
        - if: win
          then: Library/lib/x64/nvml.lib
      include:
        - if: win
          then: nvml.h
  - if: linux
    then:
      requirements:
        run:
          - patchelf
      files:
        recipe:
          - test-rpath.sh
      script:
        - bash test-rpath.sh

about:
  homepage: https://developer.nvidia.com/cuda-toolkit
  documentation: https://docs.nvidia.com/cuda/index.html
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  summary: NVML native development links and headers
  description: NVML native development links and headers.

extra:
  recipe-maintainers:
    - conda-forge/cuda
